# Generated by Django 3.0.5 on 2020-04-11 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_youtube', '0002_users_confirm_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='confirm_password',
        ),
    ]
