# Generated by Django 3.0.5 on 2020-04-12 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_youtube', '0003_remove_users_confirm_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={},
        ),
    ]
