# Generated by Django 3.0.5 on 2020-04-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_youtube', '0004_auto_20200412_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='dislike_video',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videos',
            name='like_video',
            field=models.IntegerField(default=0),
        ),
    ]
