# Generated by Django 3.0.5 on 2020-04-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_youtube', '0005_auto_20200412_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='describe',
            field=models.TextField(null=True),
        ),
    ]
