# Generated by Django 3.0.5 on 2020-04-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_youtube', '0003_remove_users_confirm_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={},
        ),
        migrations.AddField(
            model_name='videos',
            name='dislike_video',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videos',
            name='like_video',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comments',
            name='describe',
            field=models.TextField(null=True),
        ),
    ]
